### ISSUE TITLE
Boilerplate 세팅

### ISSUE THREAD

**Issue by com-maeng** [com-maeng/cali#1]
### TODO

- [x] VSCode 개발 환경 세팅
- [x] Django 템플릿 코드 생성
- [x] Dockerfile 및 Compose file 생성
- [x] PostgreSQL 컨테이너 세팅 (Compose file update)
- [x] Redis 컨테이너 세팅 (Compose file update)
