### ISSUE TITLE
오브젝트 스토리지 및 데이터 수집 파이프라인 PoC

### ISSUE THREAD

**Issue by com-maeng** [com-maeng/cali#10]
수집된 데이터를 적재할 클라우드 오브젝트 스토리지와 데이터 적재 파이프라인을 PoC 합니다.
별다른 데이터 변환 작업 없이 원본 그대로를 스토리지에 적재할 예정입니다.

### TODOs

- [x] 시트 접근 및 데이터 읽기
- [x] 읽은 구글 드라이브 URL로 메모리에 데이터(이미지) 적재하기
  - [x] 이미지 URL에서 폴더 URL로 변경됨에 따라 로직 수정
- [x] #15
  - [x] WebP 포맷 변환 모듈 개발
- [x] GCS 버킷에 데이터 적재하기
- [x] 시트 '적재 여부' 컬럼 업데이트하기
- [x] 로깅 고도화 (더 많은 로그 수집)

> 전체 파이프라인 구축 이후 진행

- [ ] ~~파이프라인 모듈 전체 리팩토링~~ 
- [ ] ~~pytest 기반 테스트 코드 작성~~
