### ISSUE TITLE
Django to Spring Boot

### ISSUE THREAD

**Issue by com-maeng** [com-maeng/cali#103]
## Description

웹 백엔드 애플리케이션 프레임워크를 Django에서 Spring Boot로 마이그레이션 합니다.
기존의 Django 코드베이스를 지우고, 새로운 Spring Boot 코드베이스가 추가됩니다.

## TODO

- [x] Django 코드베이스 제거
- [x] Spring Boot 버전 서칭 및 환경 세팅
- [x] Spring Boot 프로젝트 생성
- [x] IDE 세팅
- [x] 개발환경 실행 후 Hello World 테스트
- [x] Django 대비 Spring Boot가 어떤 장점을 가지고 있는지 숙지

**Comment by com-maeng** [comment]
@AMinSC 성철님 일전에 말씀드렸던 대로 Spring Boot가 Django 대비 어떤 장점을 가지고 있는지 숙지해두시면 좋을 것 같습니다요옹
