### ISSUE TITLE
Spring Boot Development Environment Configuration

### ISSUE THREAD

**Issue by com-maeng** [com-maeng/cali#104]
## Description

Spring Boot 애플리케이션 개발환경을 기존 Docker Compose 환경에 추가합니다.
DB, 검색엔진 등 다른 Docker Container 컴포넌트와 상호작용이 가능하도록 합니다.

## TODO

- [x] Spring Boot 빌드 서칭
- [x] DB(Postgres) 연결을 위한 Spring Boot 의존성 추가 및 설정
- [x] 개발환경 Dockerfile 및 Docker Compose 작성

**Comment by com-maeng** [comment]
작업 미완료로 Sprint 1 종료

**Comment by com-maeng** [comment]
> 작업 미완료로 Sprint 02 종료
