### ISSUE TITLE
Develop Meilisearch API Client Module for Spring Boot

### ISSUE THREAD

**Issue by com-maeng** [com-maeng/cali#105]
## DESCRIPTION

Spring Boot 애플리케이션에서 Meilisearch API를 호출할 수 있도록 모듈을 구현합니다.
API를 호출하여 index 조회, document 질의 등을 수행할 수 있습니다.

## TODO

- [x] Python으로 작성된 Config 클래스를 Java로 migration
- [x] Python으로 작성된 Search 클래스를 Java로 migration
- [x] Search Test code

## NOTE

Meilisearch API != Meilisearch 관리

**Comment by com-maeng** [comment]
작업 미완료로 Sprint 1 종료

**Comment by com-maeng** [comment]
> 작업 미완료로 Sprint 02 종료

**Comment by com-maeng** [comment]
👍🏻

**Comment by com-maeng** [comment]
> 작업 미완료로 Sprint 03 종료
