### ISSUE TITLE
작품 상세 조회 페이지 초안 디자인

### ISSUE THREAD

**Issue by com-maeng** [com-maeng/cali#106]
## Description

특정 작품을 선택했을 때 나타나는 '작품 상세 조회' 페이지의 초안을 디자인 합니다.
~~디자인 후 피드백을 취합하여 다음 이슈에 적용합니다. (디자인 업데이트)~~ 현 이슈에서 핸들링

## TODO
- [x] '작품 상세 조회' 페이지 초안 작업
- [x] '격자 아이콘 적용' 페이지 초안 작업
- [x] '이미지 좌/우 반전 아이콘 적용' 페이지 초안 작업
- [x] '작품 상세 조회_클릭 후' 페이지 초안 작업

###  + 피드백 이슈 목록
- [x] 격자 색상 변경

## Note

~~피드백 후 반영은 새로운 이슈에서 진행하는 것으로 하겠습니다.~~

**Comment by com-maeng** [comment]
@jwhan12 지원님! 요거 예정대로 익일 중으로 완료 가능하실지 확인 한 번만 부탁드려용~

**Comment by com-maeng** [comment]
혹시 늦어지실 것 같으면 부담없이 편하게 말씀해주셔도 됩니닷!

**Comment by jwhan12** [comment]
넵 내일 완료되는대로 피드백 요청드리도록 하겠습니다!

**Comment by com-maeng** [comment]
> 작업 미완료로 Sprint 1 종료

**Comment by jwhan12** [comment]
현 피드백 이슈 목록에서 
'아이콘 두께 조정'은 [아이콘셋 리디자인 #107 ](https://github.com/com-maeng/cali/issues/107)에서 진행될 예정이며,
'이미지에 대한 데이터 확인 페이지 작업'은 현재 단계에서 따로 구현하지 않는 것으로 확정했습니다.
