### ISSUE TITLE
아이콘셋 리디자인

### ISSUE THREAD

**Issue by com-maeng** [com-maeng/cali#107]
## DESCRIPTION

기존의 아이콘셋을 아이콘 디자인 가이드라인에 맞게 수정합니다.
가이드라인 레퍼런스를 먼저 리서칭하고, 해당 레퍼런스에 맞게 수정 작업을 진행합니다.

## TODO

- [x] 레퍼런스 리서치
- [x] 수정 작업 필요한 아이콘 리스트 정리
- [x] 아이콘 프로세스 작성
- [x] 디자인툴 (Photoshop 또는 Illustrator) 확정
- [x] 아이콘 수정 작업 후 피드백 요청
- [ ] 수정된 아이콘 Figma UI에 적용

## NOTE

@jwhan12 레퍼런스 리서칭 먼저 해주세용~

**Comment by com-maeng** [comment]
작업 미완료로 Sprint 1 종료

**Comment by jwhan12** [comment]
아이콘셋 리디자인 작업에 참고할 레퍼런스입니다. (차후 추가 예정)
- [Apple Human Interface Guidelines | Icons](https://developer.apple.com/design/human-interface-guidelines/icons)
- [신입 디자이너들이 알아두면 좋은 아이콘 디자인 프로세스 & 팁(Tip)](https://blog.rightbrain.co.kr/?p=6513#)
- [아이콘 그리기 전에 고려할 것들](https://yeun.github.io/2014/07/14/draw-icons-base.html#fn:icons_style)

**Comment by com-maeng** [comment]
> 작업 미완료로 Sprint 02 종료

**Comment by com-maeng** [comment]
> 작업 미완료로 Sprint 03 종료
