### ISSUE TITLE
Improve Hanja Image Segmentation Performance

### ISSUE THREAD

**Issue by com-maeng** [com-maeng/cali#112]
## Description

배치 데이터 파이프라인 중 서예 작품에서 한자 이미지를 추출하는 모듈의 성능을 고도화 합니다.
현재 한자가 식별이 되어도 정확하게 한자 이미지(박스)가 분리되지 않는 문제가 있습니다.
기존의 Tesseract를 건드려본 뒤 이슈가 쉽게 해결되지 않는 경우, Vision AI 같은 외부 API를 사용하는 방식을 고려합니다.

## TODO

- [x] ~~Tesseract 옵션 조절 및 테스트~~ Dropped
- [x] 외부 API 리서칭 및 실험
- [x] 한자 이미지 분리 모듈(OCR) 코드 수정

**Comment by com-maeng** [comment]
> Tesseract 옵션 조절 및 테스트

버티컬로 된 한자 고어를 OCR 해야 하는 고난도 작업에는 Tesseract가 적합하지 않은 툴로 판단되어 외부 API 리서칭 태스크를 진행

**Comment by com-maeng** [comment]
> 24.12.16 Sprint 02에서 계속 진행
