### ISSUE TITLE
Deploy Artwork Data Pipeline

### ISSUE THREAD

**Issue by com-maeng** [com-maeng/cali#115]
## DESCRIPTION

서예 작품 데이터 ELT 파이프라인을 배포합니다.
기존 개발환경에서의 이슈를 최종적으로 확인하고 클라우드 환경에 배포될 예정입니다.
배포된 파이프라인은 [작품 수집/검수 시트](https://docs.google.com/spreadsheets/d/1joBAmQrE5giaHD6304RHJOZLyaRef9M3_chTnyFsfvA/edit?gid=0#gid=0)에 작품을 수시로 추가할 수 있는 기반이 됩니다.

## TODO

- [x] 소스 코드 리뷰
    - [x] Dockerfile 수정 → Tesseract 패키지 제거
    - [x] gcloud CLI 스크립트
        - [x] `data/push_docker_image.sh`
        - [x] `data/sync_cloud_run_job.sh`
- [x] `.env` 파일 리뷰
- [x] 개발환경 Artifact Registry 리뷰
- [x] 개발환경 Cloud Run Job 리뷰
    - [x] 스프레드 시트 정리 (작품 수집/검수 시트)
    - [x] 구글 드라이브 정리 (비작품 이미지 삭제)
    - [x] 매뉴얼 실행 → 총 19분 08초 소요
        - [x] Cloud Run 타임아웃 이슈(`ArtworkDataPipeline`) → #142 
        - [x] OCR 한자 이미지 Coordinate 관련 이슈 (box 값 파싱, 이상 좌표값)
        - [x] `MediaIoBaseDownload.next_chunk()` Timeout 이슈
        - [x] HanjaDataPipeline 병목현상
          - [x] googleapiclient.http.HttpRequest.execute() - num_retries 옵션 명시
    - [x] Cloud Scheduler 세팅
- [ ] 배포환경 최종 세팅 (Artifact Registry, Cloud Run, Google Sheets/Drive, Google Cloud Storage)
- [ ] 작품 수집/검수 관련 팀 내부 공지

## NOTE

@AMinSC @jwhan12 일전에 아래 댓글로 말씀드렸던 파이프라인 배포 이후 작품 수집/검수 관련 공지가 빠르면 오늘부터 3-4일 내로 진행될 예정입니다.
미리 공유드립니다!

**Comment by com-maeng** [comment]
@AMinSC @jwhan12 해당 이슈가 해결되면 상시적으로 작품 수집과 검수 작업이 이루어질 예정이니, 참고 부탁드립니다.
추후 디코로 한 번 더 공지 드릴게요!
