### ISSUE TITLE
Design iOS Application Launch Screen

### ISSUE THREAD

**Issue by com-maeng** [com-maeng/cali#139]
## DESCRIPTION

iOS 애플리케이션이 실행될 때, 디바이스에 표시되는 첫 화면을 디자인합니다.
디자인 결과물을 토대로 Xcode Storyboard를 제작할 예정입니다. (By @com-maeng)

## TODO

- [ ] 런치 스크린 디자인 가이드라인 등 레퍼런스 참고
- [ ] 런치 스크린 디자인 작업 진행
- [ ] 디자인 작업물 피드백 진행 (cc. @com-maeng, @AMinSC)
- [ ] 피드백 반영 및 마무리

**Comment by com-maeng** [comment]
> 작업 미완료로 Sprint 04 종료

**Comment by com-maeng** [comment]
[보류]
