### ISSUE TITLE
Develop Xcode Storyboard for Launch Screen

### ISSUE THREAD

**Issue by com-maeng** [com-maeng/cali#140]
## DESCRIPTION

#139 에서 디자인된 런치 스크린을 기반으로 Xcode Storyboard를 작성합니다.
Storyboard 개발 후 디자이너와 리뷰를 진행할 예정입니다. cc. @jwhan12 

## TODO

- [ ]  Storyboard 기초 파악
- [ ]  Storyboard 작성 및 테스트
- [ ]  결과물 리뷰 w. @jwhan12

**Comment by com-maeng** [comment]
> 작업 미완료로 Sprint 03 종료

**Comment by com-maeng** [comment]
[보유]
