### ISSUE TITLE
Fix Download/Upload Bottleneck within ArtworkDataPipeline

### ISSUE THREAD

**Issue by com-maeng** [com-maeng/cali#142]
## DESCRIPTION

아래 ArtworkDataPipeline에서 발생하는 병목현상들을 해결합니다.
- Download: Google Drive에서 작품 이미지를 다운로드 받을 때 발생하는 병목
- Upload: Cloud Storage 버킷에 이미지를 업로드 할 때 발생하는 병목

상기 병목현상으로 Cloud Run Job에서 타임아웃이 발생하고, 이로 인해 한자 이미지가 유실없이 적재되었다고 보장할 수 없는 문제가 있습니다.

## TODO

- [x] 병목현상 해결법 아이데이션
- [ ] 이미지 download 관련 소스 코드 수정
- [x] 이미지 upload 관련 소스 코드 수정
