### ISSUE TITLE
Advance Hanja Dictionary

### ISSUE THREAD

**Issue by com-maeng** [com-maeng/cali#143]
## DESCRIPTION

한자 사전에 더 많은 한자를 추가합니다.
현재 작품 데이터 파이프라인 내 작품 이미지에서 추출된 한자가 라벨링되지 않고 버려지는 이슈가 있습니다.
이를 해결하기 위해 한자 사전에 더 많은 한자를 추가하여 버려지는 한자를 최소화 합니다.

## TODO

- [ ] 한자 추가 방법 리서칭
  - [ ] 한자 사전용 외부 API 리서칭 (필요 시)
- [ ] 한자 사전 파일 수정 (필요 시)
- [ ] 한자 사전 로딩 소스 코드 수정 (필요 시)
