### ISSUE TITLE
Refine artwork data pipeline logging codes

### ISSUE THREAD

**Issue by com-maeng** [com-maeng/cali#147]
## DESCRIPTION

작품 데이터 파이프라인 내 로깅 코드를 수정합니다.
- elt_pipeline.log 가 아닌 표준 출력으로 내보내도록
  - 로그 메시지를 Cloud Run Job 로그에서 확인할 수 없음
- 로그 메시지가 일관되도록 (문구 및 형식 수정)
- 불필요한 로그 메시지 삭제
- 필요한 로그 메시지 추가

## TODO

- [ ] 로그 메시지 출력 코드 수정
- [ ] 로그 메시지 톤 확정
- [ ] 불필요 로깅 코드 삭제
- [ ] 신규 로깅 코드 추가
