### ISSUE TITLE
Configure Meilisearch(search engine) development environment

### ISSUE THREAD

**Issue by com-maeng** [com-maeng/cali#148]
## DESCRIPTION

개발환경 메일리서치 서버 한자사전 로딩 (Docker Compose)

## TODO

- [ ] [메일리서치 독스](https://www.meilisearch.com/docs/learn/getting_started/what_is_meilisearch) 톺아보기
- [ ] 기존 소스 코드 파악
- [ ] 소스 코드 수정

**Comment by com-maeng** [comment]
> 작업 미완료로 Sprint 04 종료
