### ISSUE TITLE
이미지 처리 모듈 구현 'data.utils.image_module'

### ISSUE THREAD

**Issue by com-maeng** [com-maeng/cali#34]
이미지 전처리, OCR, 크롭(편집) 작업으로 구성된 이미지 모듈을 구현합니다.
모듈에는 다양한 이미지 처리 관련 작업들이 추가될 예정입니다 :)

### TODO

- [x] ArtworkDataPipeline 모듈 로직 수정 (Artwork 리스트 반환 등)
- [x] 이미지 전처리 로직 및 테스트 작성
- [x] 이미지 OCR 로직 및 테스트 작성
- [ ] ~~이미지 크롭 로직 및 테스트 작성~~
